services:
  app:
    image: ghcr.io/mbenitog/meshtastic-site-spain:latest
    ports:
      - 8080:80
    restart: unless-stopped
    networks:
      - app-network

  ultra-backend:
    image: ghcr.io/mbenitog/meshtastic-site-spain-ultra:latest
    ports:
      - 8000:8000
    volumes:
      - ultra-cache:/app/.cache
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:

volumes:
  ultra-cache:
